packaging_format = 2

id = "crabfit"
name = "Crab Fit"
description.en = "Enter your availability to find a time that works for everyone"
description.fr = "Trouver un temps correspondant à tout le monde en rentrant vos disponibilités"

version = "1.0~ynh4"

maintainers = ["limaanto"]

[upstream]
license = "GPL-3.0-only"
website = "https://crab.fit"
demo = "https://crab.fit"
admindoc = "https://github.com/GRA0007/crab.fit"
userdoc = "https://github.com/GRA0007/crab.fit"
code = "https://github.com/GRA0007/crab.fit"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "500M"
ram.build = "500M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.main]
        # No releases currently exist in the repo, looking forward to improving that
        url = "https://github.com/GRA0007/crab.fit/archive/628f9eefc300bf1ed3d6cc3323332c2ed9b8a350.zip"
        sha256 = "cc87276d26242a90f32f1462319f0cff35c576f6c438cc20e68601f26701b33b"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.ports]
    main.default = 3000
    api.default = 3001

    [resources.apt]
    packages = "postgresql, pkg-config, libssl-dev"

    [resources.database]
    type = "postgresql"
