#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
ynh_script_progression --message="Removing $app service integration..." --weight=1
yunohost service remove "${app}-back"
yunohost service remove "${app}-front"

ynh_remove_systemd_config --service="${app}-back"
ynh_remove_systemd_config --service="${app}-front"
ynh_secure_remove --file="/etc/systemd/system/$app.target"

ynh_remove_nginx_config

ynh_remove_logrotate

ynh_secure_remove --file="/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
